#ifndef INC_CTRLR_CONFIG_H_
#define INC_CTRLR_CONFIG_H_

/*
 * ctrlr_config.h
 *
 * The project's one compile-time config file -- board/firmware
 * IDENTITY (HW_BOARD_NAME/REV, FW_VERSION_STRING) and general
 * controller-BEHAVIOR settings (HRTIM_NUM_CHANNELS, GDS_FAULT_POLARITY)
 * together, matching the sibling PFM-STM32G474 project's single
 * supply_config.h. This was briefly split (2026-09-08: identity stayed
 * in version.h, behavior moved here) on the reasoning that identity and
 * behavior are different KINDS of thing -- re-condensed the same day,
 * per project decision, back to one file. version.h no longer exists;
 * don't recreate it.
 *
 * (Module-local, self-contained flags are a further, older exception --
 * e.g. BOOT_JUMP_FEATURE_ENABLED lives in boot_jump.h itself, because
 * that module's whole design point is being independently removable in
 * one place. Don't move flags like that here.)
 */

/* build_target.h (gitignored, regenerated by python/gen_build_target.py
 * before every build -- see that script's own header comment) selects
 * BUILD_TARGET_CONTROLLER vs BUILD_TARGET_SIMULATOR for this whole
 * firmware image. Included here, not in a dozen individual .c files,
 * specifically because ctrlr_config.h is already included almost
 * everywhere in this project -- one include point covers the whole
 * codebase's #ifdef needs. */
#include "build_target.h"

/* --------------------------------------------------------------------------
 * Board/product identity. HW_BOARD_REV is a placeholder -- set it to
 * match this build's actual PCB silkscreen revision and bump it on
 * every hardware respin so *IDN's report always matches what's
 * physically in hand.
 *
 * HW_BOARD_NAME is target-conditional as of 2026-09-17: the simulator
 * build reports a visibly distinct product string (`-SIM` suffix) so a
 * host can never mistake which physical board it's actually talking
 * to over `*IDN?` -- the whole reason this distinction exists is to
 * make it impossible to confuse a controller-target flash with a
 * simulator-target one by accident. */
#if defined(BUILD_TARGET_SIMULATOR)
#define HW_BOARD_NAME     "WHAM-XREX-PFMG474-SIM"
#else
#define HW_BOARD_NAME     "WHAM-XREX-PFMG474"
#endif
#define HW_BOARD_REV      "REVA"

/* Firmware identity. Bump on every release the way the sibling
 * PFM-STM32G474 project does (FW_VERSION_STRING in its
 * supply_config.h). Reset to v0.1 at this project's own start
 * (2026-09-09, reseeded from WHAM-PFMG474-V4 at commit de83324 -- see
 * AGENTS.md and docs/changelog.txt) -- not a continuation of that
 * project's v0.6 lineage, a fresh one for this one. */
#define FW_VERSION_STRING "v0.1"

/* --------------------------------------------------------------------------
 * GPOut:ENAble (PC13, "GPOut_Enable_Pin") / PWMAlt:ENAble (PC15,
 * "PWM_Alt_Enable") boot-time default level -- compile-time config,
 * added 2026-09-18 per direct instruction, applying to EVERY build of
 * this board (BUILD_TARGET_CONTROLLER and BUILD_TARGET_SIMULATOR
 * alike -- these two pins/commands have no target-specific behavior at
 * all, unlike most of this project's XR-channel logic).
 *
 * Both default to `1` (HIGH) here, matching the ORIGINAL 2026-09-17
 * direct instruction ("By default, keep it HIGH... default output
 * HIGH") -- that original wording is now satisfied via this named
 * constant instead of the hardcoded `GPIO_PIN_SET` main.c used before
 * today, so the default can be changed in ONE place without touching
 * main.c's GPIO_InitTypeDef blocks at all. Independent of, and
 * unaffected by, the RUNTIME `GPOut:ENAble <0|1>`/`PWMAlt:ENAble <0|1>`
 * commands (commands.c) -- those two mechanisms coexist on purpose:
 * this constant only decides what the pin reads at the instant of
 * boot, before any serial command has ever been sent; the runtime
 * command is what lets an operator change it afterward. */
#define GPOUT_ENABLE_DEFAULT_HIGH    (1U)
#define PWMALT_ENABLE_DEFAULT_HIGH   (1U)

/* --------------------------------------------------------------------------
 * HRTIM channel count
 *
 * REPURPOSED, 2026-09-09, for the closed-loop PID architecture (see
 * pid.h and docs/changelog.txt's design-decision entry): this used to
 * mean "how many channels are phase-locked and evenly spaced around a
 * shared carrier" (WHAM-PFMG474-V4's switching-supply meaning, and
 * still literally true of the code this was reseeded from). It now
 * means "how many of the 4 Transrex channels are active" --
 * HRTIM_NUM_CHANNELS independent PFM output channels (Possibility 3:
 * per-channel HRTIM update-on-own-rollover, ResetTrigger=NONE,
 * UpdateTrigger=NONE, ResetUpdate=ENABLED), each running its own PID
 * loop against its own PFM_Input feedback channel, with NO phase
 * relationship between them at all. docs/pin_mapping_v4.csv wires out
 * all 6 HRTIM1 channel pairs (A-F / U,V,W,X,Y,Z) on this board; this
 * selects how many of them PID.c actually drives, as a real
 * compile-time setting -- fix it here, rebuild, reflash, same
 * not-runtime-modifiable reasoning as before.
 *
 * 4, not the sibling project's default of 3 -- the Transrex spec (this
 * project's whole reason for existing, docs/Transrex/) is 4
 * independent units. Range kept at 1-5 (unchanged from before): the
 * HRTIM Master timer's own repetition event is what drives the PID
 * heartbeat now (see pid.h), so the OLD 1-5 constraint (Master's 4
 * compare registers, MCMP1R-MCMP4R, phase-locking channels A-E) no
 * longer actually applies here -- Master has no per-channel phase
 * relationship left to run out of registers for. Left at 5 anyway
 * (not widened to 6) simply because nobody has re-verified a 6th
 * independent channel on this board yet, not because of the old
 * register-count reason -- raise it if a real need for a 5th/6th
 * Transrex channel ever shows up, after checking HRTIM1_FullInit()'s
 * unconditional channels-0..5 loops still make sense at N=6.
 *
 * Channels beyond HRTIM_NUM_CHANNELS (up through Timer F) stay
 * pin/dead-time-reserved but unlocked and are never started -- exactly
 * as before this repurposing, see HRTIM1_FullInit()'s own comments.
 * -------------------------------------------------------------------------- */
#define HRTIM_NUM_CHANNELS  (4U)

#if (HRTIM_NUM_CHANNELS < 1U) || (HRTIM_NUM_CHANNELS > 5U)
#error "HRTIM_NUM_CHANNELS must be 1-5 -- see the comment above it in " \
       "ctrlr_config.h."
#endif

/* --------------------------------------------------------------------------
 * PID control-loop heartbeat rate (compile-time)
 *
 * Added 2026-09-09 alongside the closed-loop PID architecture (pid.c,
 * docs/changelog.txt's design-decision entry) -- the HRTIM Master
 * repetition interrupt's rate while PID mode is running, DELIBERATELY
 * decoupled from any channel's own carrier/demand frequency (see that
 * changelog entry for the full reasoning: fixed PID sample time,
 * control bandwidth != V-to-F encoding rate). 1 kHz is a first,
 * conservative starting point -- tens of Hz to low kHz is the normal
 * range for a magnet-supply current loop; this has NOT been tuned
 * against real Transrex/magnet electrical time constants yet, revisit
 * once real bench data exists. Must yield a Master PER that fits
 * HRTIM's 16-bit register at the prescaler pid.c actually configures
 * (see HRTIM1_ConfigPidHeartbeat() in hrtim.c) -- 1 kHz at /4 prescale
 * is exactly 42500 counts (170 MHz / 4 / 1000), comfortably inside
 * 16 bits with headroom to go slower still.
 * -------------------------------------------------------------------------- */
#define PID_LOOP_RATE_HZ   (1000UL)

/* --------------------------------------------------------------------------
 * PID output frequency bounds (compile-time, hard limit)
 *
 * Added 2026-09-09 alongside the closed-loop PID architecture (pid.c)
 * -- clamps every channel's commanded output frequency (and, via
 * PID_SetSetpoint(), its setpoint) to a range HRTIM can actually
 * represent on this hardware, at the /1 prescale each channel's own
 * timer uses (hrtim.c's HRTIM1_FullInit()).
 *
 * PID_OUTPUT_MIN_HZ is a REAL hardware floor, not a tuning choice: at
 * /1 prescale, PER = HRTIM_TIMER_CLK_HZ/freq - 1 must fit in HRTIM's
 * 16-bit PER register (max 65535) -- solving for freq gives
 * 170000000/65536 = ~2594.9 Hz as the absolute lowest representable
 * frequency. Set to 3000 Hz, comfortably clear of that floor (not
 * flirting with an off-by-one at the exact boundary).
 *
 * PID_OUTPUT_MAX_HZ is NOT a hardware limit at this end (170 kHz would
 * still fit, PER=999) -- 150 kHz is a conservative starting ceiling,
 * chosen to sit within the range this exact codebase has already
 * proven clean on real hardware (its own PFM_MAX_CARRIER_FREQ_HZ,
 * below, documents 100 kHz tested clean; this is somewhat above that,
 * unverified for THIS use case -- revisit once real Transrex/magnet
 * operating-point data exists, per docs/changelog.txt's own
 * "explicitly NOT yet resolved" list on this exact point).
 * -------------------------------------------------------------------------- */
#define PID_OUTPUT_MIN_HZ  (3000UL)
#define PID_OUTPUT_MAX_HZ  (150000UL)

/* --------------------------------------------------------------------------
 * Transrex Amps<->Hz mapping (compile-time, PLACEHOLDER pending real
 * hardware characterization)
 *
 * Added 2026-09-10, the real production shot-profile design: an
 * operator programs Ramp Time / Flat Top Time / Demand Current
 * (Amps) -- see pid.h's PID_SetProfileTiming()/PID_SetProfileCurrent()
 * -- and pid.c converts that trapezoidal CURRENT trajectory to a
 * target FREQUENCY each Master tick via these calibration points:
 *
 *   PFM_TURNON_FREQ_HZ       -- the Transrex's own "turn-on"
 *                               threshold: at or below this
 *                               frequency, the supply outputs ZERO
 *                               current (a genuine hardware dead
 *                               zone, not just "small current"). Maps
 *                               to exactly 0 A, per direct
 *                               confirmation -- the ramp never
 *                               commands anything below this value.
 *                               ONE value, shared across every
 *                               channel -- unlike PFM_MAX_CURRENT_A_PER_CHANNEL
 *                               below, nothing so far indicates this
 *                               threshold itself differs per Transrex,
 *                               only the CURRENT the top of the range
 *                               produces. Revisit if bench testing
 *                               ever shows otherwise.
 *   PFM_MAX_FREQ_HZ           -- the top of the PFM frequency range,
 *                               also shared across every channel (a
 *                               property of this controller's own PFM
 *                               modulation scheme, not of any one
 *                               Transrex).
 *   PFM_MAX_CURRENT_A_PER_CHANNEL[ch]   -- PER-CHANNEL, added 2026-09-11 per
 *                               direct correction: what PFM_MAX_FREQ_HZ
 *                               actually produces is a property of
 *                               EACH PHYSICAL TRANSREX SUPPLY, not a
 *                               single number good for all four --
 *                               "100kHz corresponds to 5kA" was only
 *                               ever an approximation, and the 4
 *                               Transrexes this controller drives may
 *                               each have a genuinely different
 *                               full-range output current. See its
 *                               own comment below.
 *
 * LINEAR interpolation between the per-channel current range and
 * [PFM_TURNON_FREQ_HZ, PFM_MAX_FREQ_HZ], PLACEHOLDER, per direct
 * confirmation (2026-09-10) -- flagged, not silently assumed: the
 * ORIGINAL analog Transrex chain (docs/Transrex/
 * Transrex_Controls_Upgrade (1).pdf) describes a 0-10V signal mapping
 * to SCR firing angles 180-0 degrees, and phase-controlled rectifiers
 * are classically NONLINEAR (roughly cosine-shaped) between firing
 * angle and actual output current -- whether that nonlinearity is
 * already compensated upstream of us, or whether our frequency needs
 * to trace a matching curve instead of a straight line, is unknown
 * from here and needs real hardware characterization. AmpsToHz()
 * (pid.c) is written as one small, isolated, swappable function
 * specifically so replacing "linear" with a calibrated curve later
 * touches only that function, not the profile generator or the
 * control loop around it.
 *
 * PFM_TURNON_FREQ_HZ/PFM_MAX_FREQ_HZ are PLACEHOLDERS ("~5 kHz" /
 * "100 kHz" per direct confirmation, "hardware testing will give us a
 * more precise value") -- update once real bench characterization
 * exists, and note the range these define sits safely inside
 * [PID_OUTPUT_MIN_HZ, PID_OUTPUT_MAX_HZ] above, which stays in place
 * as the outer hardware-register safety clamp regardless of what
 * these two turn out to be. */
#define PFM_TURNON_FREQ_HZ   (5000UL)
#define PFM_MAX_FREQ_HZ       (100000UL)

/* --------------------------------------------------------------------------
 * *** MUST BE CALIBRATED BEFORE FINAL DEPLOYMENT ***
 *
 * PFM_MAX_CURRENT_A_PER_CHANNEL -- per-channel: this channel's actual real-world
 * output current (Amps) at PFM_MAX_FREQ_HZ (100 kHz). Added
 * 2026-09-11, per direct correction: "100kHz corresponds to 5kA" was
 * stated as an approximation from the start, and the 4 physical
 * Transrex supplies this controller drives may each have a genuinely
 * different full-range current -- there is no reason to expect all
 * four are identical, and nothing has actually measured any of them
 * yet. EVERY entry below is currently the SAME 6000.0f placeholder
 * (updated 2026-09-18 from an original 5000.0f -- see that value's own
 * comment below for why), which is almost certainly wrong for at least
 * some channels -- DO NOT ship/commission with these values unverified.
 *
 * REQUIRED BEFORE FINAL DEPLOYMENT: for EACH of the 4 Transrexes,
 * independently -- drive that channel (SHOT:CURRent/PID:LOOPMODE
 * open-loop is the simplest way to command a known, repeatable
 * frequency directly, e.g. via python/wham_console.py) at
 * PFM_MAX_FREQ_HZ (or as close to it as is safe to actually run) and
 * measure that Transrex's REAL output current with real
 * instrumentation (a calibrated current sensor/shunt on that
 * specific supply's output -- NOT inferred from this codebase's own
 * PFM_Input frequency feedback, which measures the PFM signal, not
 * the actual load current, and cannot itself validate this mapping).
 * Replace that channel's entry below with the measured value. Until
 * this is done, every Amps<->Hz conversion on every channel
 * (AmpsToHz(), pid.c; the shot-profile Demand Current an operator
 * programs; wham_console.py's plotted Amps axis) is only as accurate
 * as this shared placeholder -- i.e., not yet verified for ANY
 * channel, and certain to be wrong for at least some of the 4 once
 * real numbers differ.
 *
 * Indexed 0..HRTIM_NUM_CHANNELS-1 (0-based, internal convention --
 * matches every other per-channel array in this codebase), NOT the
 * 1-based wire numbering SHOT:CURRent/etc. use -- channel 1 on
 * the wire is index [0] here. Entry count MUST equal HRTIM_NUM_CHANNELS
 * exactly -- pid.c _Static_assert()s this at compile time so a
 * mismatched edit (e.g. after ever changing HRTIM_NUM_CHANNELS above)
 * fails the build loudly instead of silently reading past the array
 * or leaving a channel uninitialized. */
#define PFM_MAX_CURRENT_A_PER_CHANNEL  { 6000.0f, 6000.0f, 6000.0f, 6000.0f }   /* ch1, ch2, ch3, ch4 --
                                                                          UPDATED 2026-09-18, per
                                                                          direct confirmation
                                                                          against docs/Transrex/
                                                                          Transrex_Controls_Upgrade
                                                                          (1).pdf: that document's
                                                                          own original spec called
                                                                          for 5kA output LEMs, but
                                                                          the REAL installed LEMs
                                                                          are 6kA -- confirmed
                                                                          directly, not silently
                                                                          copied from the document.
                                                                          Still a SHARED default
                                                                          across all 4 channels
                                                                          (not yet independently
                                                                          measured per-channel) --
                                                                          the "MUST BE CALIBRATED
                                                                          BEFORE FINAL DEPLOYMENT"
                                                                          warning above still
                                                                          applies unchanged; this is
                                                                          a better shared placeholder,
                                                                          not a real per-channel
                                                                          measurement. Applies
                                                                          identically to both the
                                                                          DEMAND output and the
                                                                          FEEDBACK measurement (same
                                                                          linear AmpsToHz() mapping
                                                                          either direction, per
                                                                          direct confirmation). */

/* --------------------------------------------------------------------------
 * PID_OUTPUT_MAX_SLEW_HZ_PER_TICK -- hard per-tick output slew-rate
 * clamp (compile-time, PLACEHOLDER pending real hardware
 * characterization)
 *
 * Added 2026-09-10, in direct response to a REAL finding: an
 * independent 250 MHz DSLogic capture of channel 1's actual HRTIM
 * output pin during a real shot CONFIRMED (not just self-reported by
 * the firmware's own log) that a single bad feedback sample can make
 * PID_Update() compute and WRITE a wildly wrong output for exactly
 * one tick -- e.g. commanding ~89 kHz when the setpoint was 62 kHz --
 * before the next tick's clean feedback corrects it. Harmless on a
 * bench loopback; NOT acceptable to leave unguarded once a real
 * Transrex supply/magnet is in the loop, where a real winding/supply
 * has no reason to expect (or survive) an instantaneous multi-tens-
 * of-kHz command excursion.
 *
 * This is a HARD clamp: PID_Update() bounds every tick's actual write
 * to HRTIM1_SetChannelPeriod() to at most this many Hz of change from
 * the PREVIOUS tick's actual output, in either direction -- applied
 * to every channel, every tick, regardless of open- or closed-loop
 * mode or which code path computed the desired value (PID math, a
 * plain PID_SetSetpoint() step, PID_StartRamp(), or the shot-profile
 * generator). It sits AFTER [PID_OUTPUT_MIN_HZ, PID_OUTPUT_MAX_HZ]
 * range-clamping, as a second, independent stage -- see pid.c's
 * ClampOutputSlew(). The existing directional anti-windup logic
 * (pid.c, PID_Update()) treats slew-clamping exactly like range-
 * clamping: integration is blocked only when it would push further
 * into whichever limit actually bound the output that tick.
 *
 * TRADE-OFF, understood and accepted, not accidental: this also
 * bounds LEGITIMATE fast PID correction (e.g. a large first-tick
 * proportional response to a big initial error) -- the clamp cannot
 * distinguish "the PID is correctly reacting hard to a real error"
 * from "the PID is reacting to one bad sample." That's the whole
 * point of a HARD clamp per direct instruction: it protects real
 * downstream hardware from the failure mode directly, rather than
 * trying to first correctly classify every possible bad sample (the
 * other option discussed -- outlier-rejecting PfmInput_
 * ConsumeAveragePeriod()'s result before it ever reaches PID math --
 * remains a reasonable complementary addition later, not a
 * replacement for this).
 *
 * VALUE IS A PLACEHOLDER: chosen to sit comfortably above this
 * project's own real shot-tracking needs observed on the bench
 * loopback (normal PID correction during an actual 1s-ramp shot ran
 * on the order of a few hundred to low thousands of Hz/tick -- see
 * docs/changelog.txt's 2026-09-10 entries) while meaningfully
 * suppressing the observed ~20000-90000 Hz single-tick glitch
 * magnitude -- NOT derived from any real Transrex/magnet slew
 * tolerance, which is unknown from here. Revisit once real hardware
 * characterization exists, same status as PFM_TURNON_FREQ_HZ/
 * PFM_MAX_FREQ_HZ above. In Hz per PID_Update() tick (one Master
 * heartbeat, PID_DT_SEC = 1/PID_LOOP_RATE_HZ) -- NOT Hz/second. */
#define PID_OUTPUT_MAX_SLEW_HZ_PER_TICK  (2000UL)

/* --------------------------------------------------------------------------
 * FAULT_RAMP_DOWN_TIME_S -- General Fault open-loop ramp-down duration
 * (compile-time, PLACEHOLDER -- "a pre-defined period of seconds
 * chosen for the ramp," per direct instruction, 2026-09-13)
 *
 * On a General Fault (state_machine.c's HandleGeneralFault()) detected
 * while FIRING, every channel that was actively outputting immediately
 * begins an OPEN-LOOP linear ramp from whatever frequency it happened
 * to be at down to PFM_TURNON_FREQ_HZ (0A) over exactly this many
 * seconds -- regardless of where in the programmed shot profile it
 * was, and with no PID/feedback correction at all (see
 * PID_BeginFaultRampDown()/ProcessFaultRampDown(), pid.c). Once every
 * participating channel reaches the floor, its HRTIM output is
 * disabled (HRTIM1_SetChannelOutputEnable()) and the controller
 * settles into a fully-stopped FAULT state.
 *
 * 1.0 second is a first, reasonable-sounding guess -- fast enough to
 * reach a safe state quickly, not so fast it's effectively a step
 * change. NOT derived from any real Transrex/magnet requirement (how
 * fast can this hardware actually tolerate ramping down? is there a
 * reason it should be faster/slower than a normal shot's own down-ramp,
 * 5-15s nominal?) -- unknown from here, needs a real decision, same
 * "placeholder, revisit" status as PFM_TURNON_FREQ_HZ/PFM_MAX_FREQ_HZ/
 * PID_OUTPUT_MAX_SLEW_HZ_PER_TICK above. */
#define FAULT_RAMP_DOWN_TIME_S  (1.0f)

/* --------------------------------------------------------------------------
 * Generic fault-pin polarity constants (compile-time)
 *
 * Added 2026-09-17 (as XREX_POLARITY_*, scoped to the section just below);
 * RENAMED same day, later, to this generic FAULT_POLARITY_* form once a
 * second, unrelated consumer showed up -- this is a plain "which raw
 * level means healthy" concept with nothing XREX-specific about it, so
 * a generic name is the honest one now that it's shared. (That second
 * consumer, EMERGENCY_STOP_POLARITY, was REMOVED 2026-09-21 with the
 * E-stop feature itself -- see docs/changelog.txt.) Pure rename, no
 * value/behavior change;
 * xrex_io.c's BitIsFault() and every XR_*_POLARITY setting below were
 * updated to match.
 *
 * FAULT_POLARITY_NORMALLY_HIGH -- pins read HIGH in good operation; a LOW
 *                                  reading (a falling edge from healthy)
 *                                  is a fault.
 * FAULT_POLARITY_NORMALLY_LOW  -- pins read LOW in good operation; a HIGH
 *                                  reading is a fault. */
#define FAULT_POLARITY_NORMALLY_HIGH   (0U)
#define FAULT_POLARITY_NORMALLY_LOW    (1U)

/* --------------------------------------------------------------------------
 * XREX per-channel fault-pin polarity (compile-time)
 *
 * Added 2026-09-17, per direct request -- REPLACES the old
 * GDS_FAULT_POLARITY single shared setting below with four independent
 * ones, one per fault CATEGORY. docs/pin_mapping_v4.csv's new "XREX Pin
 * Name" column labels the same 12 PE0..PE11 pins (previously
 * undifferentiated GateDriverStatus_01..12, see gate_driver.h) as each
 * of XR1..XR4's own _WATER_FLT/_TMP_FLT/_ENERPRO_FLT signals, and adds
 * 4 new _OCP pins (PF4/PF5/PF8/PF12) that had no real hardware
 * detection wired up anywhere before now. xrex_io.c owns the actual
 * per-channel-gated fault-evaluation logic (see that file's own header
 * comment); these four settings are its only per-category config.
 *
 * All four default to NORMALLY_HIGH, per direct confirmation --
 * *** DELIBERATELY THE OPPOSITE of the OLD GDS_FAULT_POLARITY value
 * this section replaces *** (GDS_NORMALLY_LOW, confirmed 2026-09-08
 * against real hardware -- see docs/changelog.txt's 2026-09-08 entry
 * for that finding's own history: a GDS? snapshot showed 11 of 12 pins
 * reading LOW with only one reading HIGH, consistent with LOW being the
 * healthy state at the time). Not a mistake, not a re-guess -- flagged
 * directly and confirmed: "During normal non-faulted operation, these
 * pins will be normally high," overriding that earlier finding for
 * Water/Temp/Enerpro specifically. Recorded here rather than silently
 * applied, since it contradicts prior real-hardware data on the exact
 * same physical pins. OCP (a genuinely new, never-before-wired signal,
 * on different pins entirely) has no conflicting prior data and
 * defaults NORMALLY_HIGH per the same direct instruction.
 *
 * Independently configurable (not one shared value like the old
 * GDS_FAULT_POLARITY) -- a real hardware difference between fault
 * categories, or between them and OCP's own separate pins, is
 * plausible and worth being able to express without a code change.
 *
 * GateDriver_CheckFault() (gate_driver.c) now delegates its own fault
 * decision to XrexIo_EvaluateGateDriverFault() (xrex_io.c), which
 * consults these four settings (plus per-channel enable gating)
 * instead of the old single GDS_FAULT_POLARITY check. GDS? (commands.c)
 * remains a raw, polarity-agnostic HIGH/LOW readback either way -- see
 * gate_driver.h's own comment; XREX:CHANnel:STATus? (commands.c, new)
 * is the XR-labeled equivalent for these specific signals. */
#define XR_WATER_FLT_POLARITY     FAULT_POLARITY_NORMALLY_HIGH
#define XR_TMP_FLT_POLARITY       FAULT_POLARITY_NORMALLY_HIGH
#define XR_ENERPRO_FLT_POLARITY   FAULT_POLARITY_NORMALLY_HIGH
#define XR_OCP_FLT_POLARITY       FAULT_POLARITY_NORMALLY_HIGH

/* Emergency-stop (PG10) input polarity -- REMOVED 2026-09-21 with the
 * E-stop feature itself: PG10 turned out to be electrically tied to
 * NRST, not a usable GPIO (see main.c's MX_GPIO_Init() comment and
 * docs/changelog.txt). A future E-stop must use a genuinely free input
 * pin and re-settle the fail-safe polarity question afresh. */

/* --------------------------------------------------------------------------
 * PFM carrier frequency ceiling (compile-time, hard limit)
 *
 * Added 2026-09-09 after a real-hardware frequency-ramp capture test
 * (see docs/changelog.txt) found that this board's PWM output can
 * intermittently glitch on a frequency-CHANGING table -- an occasional
 * genuinely missing real pulse on the wire, confirmed via DSLogic, not
 * just a capture-side artifact -- starting somewhere around 85 kHz and
 * getting more frequent up toward 140 kHz. Root cause is an open
 * investigation (a suspected HRTIM shadow/preload-register race in how
 * PFM_CycleBoundaryHandler applies each new table entry -- see
 * docs/changelog.txt's 2026-09-09 entries). Until that's actually
 * fixed and re-verified, every TABLE:STEP entry's implied carrier
 * frequency is capped here and rejected with ERR 10
 * (commands.c's cmd_table_step()) rather than silently accepted and
 * possibly glitching.
 *
 * 100 kHz is the documented, tested boundary -- every constant-100 kHz
 * test this project has run, going back to the very first PWM
 * bring-up, has been clean, and the ramp test's first several steps
 * (all below 85 kHz) never glitched either. This is NOT a claim that
 * 100 kHz is provably safe in general, just the boundary this project
 * has actual evidence for -- raise it only after the shadow/preload
 * fix lands and is itself re-verified on real hardware at whatever new
 * ceiling is proposed.
 * -------------------------------------------------------------------------- */
#define PFM_MAX_CARRIER_FREQ_HZ  (100000UL)

#endif /* INC_CTRLR_CONFIG_H_ */
