#!/usr/bin/env python3
"""
gen_build_target.py -- generates Core/Inc/build_target.h, which selects
CONTROLLER vs SIMULATOR firmware from this SAME repo (added 2026-09-17,
per direct request -- a Transrex simulator, a second identical board
that plays the role of the Transrex for full-stack bench testing,
sharing this project's HAL drivers, uart.c/cmd_parser.c's SCPI
framework, and pfm_input.c's already-working capture code rather than
forking into a separate project).

Exactly the same pattern as gen_git_version.py (see that script's own
header comment) -- a small generated header, regenerated before every
build by wham_build.py, gitignored so it's never accidentally committed
stale. Using a generated HEADER rather than a `-D` compiler flag is
deliberate: this project's Debug/ build is CubeIDE-generated make files
(Debug/Core/Src/subdir.mk) with per-file compile commands baked in --
adding a new "-D" flag there means editing that fragile, auto-generated
file (a real, already-documented gotcha, see AGENTS.md's "Adding a new
source file" section for the exact same class of issue). A header that
virtually every source file already transitively includes via
ctrlr_config.h needs no Makefile changes at all.

Usage:
  python3 python/gen_build_target.py --target controller   # default
  python3 python/gen_build_target.py --target simulator
"""

import argparse
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)  # this script lives in python/
OUT_PATH = os.path.join(PROJECT_DIR, "Core", "Inc", "build_target.h")


def main():
    ap = argparse.ArgumentParser(description="Generate Core/Inc/build_target.h")
    ap.add_argument("--target", choices=["controller", "simulator"], default="controller",
                     help="which firmware to select (default: controller)")
    args = ap.parse_args()

    define = "BUILD_TARGET_SIMULATOR" if args.target == "simulator" else "BUILD_TARGET_CONTROLLER"

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write(
            "/* AUTO-GENERATED by python/gen_build_target.py -- DO NOT EDIT BY\n"
            " * HAND, DO NOT COMMIT (gitignored, see .gitignore's own comment\n"
            " * on why). Regenerated before every build by python/wham_build.py's\n"
            " * --target flag (default: controller). Selects CONTROLLER vs\n"
            " * SIMULATOR firmware from this same repo -- see AGENTS.md and the\n"
            " * Transrex-simulator plan for the full design. Included via\n"
            " * ctrlr_config.h, which is already included almost everywhere in\n"
            " * this project. */\n"
            "#ifndef BUILD_TARGET_H\n"
            "#define BUILD_TARGET_H\n"
            "\n"
            f"#define {define}   1\n"
            "\n"
            "#endif /* BUILD_TARGET_H */\n"
        )

    print(f"[build-target] wrote {OUT_PATH} -- {define}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
