#!/usr/bin/env python3
"""
gen_git_version.py -- generates Core/Inc/git_version.h from the
current git state, so a build bakes in exactly which commit it was
built from. cmd_idn() (commands.c) includes it in *IDN?'s reply,
specifically so a host can always tell which firmware a board is
actually running, not just what's supposed to be flashed.

Run this BEFORE every build that's meant to be flashed -- normally you
don't need to invoke it directly: python/wham_build.py does this step
automatically as part of one build+bin command. Called directly only
if you're driving `make` yourself for some other reason (debugging the
build itself, say) and still want an accurate git_version.h.

Core/Inc/git_version.h is gitignored on purpose -- see .gitignore's own
comment on why (its whole job is capturing "what commit was THIS build
from," which is redundant with git's own history for a clean build,
and would just create merge noise if tracked).

Usage:
  python3 python/gen_git_version.py
"""

import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)  # this script lives in python/
OUT_PATH = os.path.join(PROJECT_DIR, "Core", "Inc", "git_version.h")

HASH_LEN = 8  # matches this project's own existing convention for citing a
              # commit informally (e.g. AGENTS.md's "reseeded ... at de83324")


def run_git(args):
    """Returns stdout (stripped) or None if git itself failed/isn't
    available -- NEVER raises, since a missing git_version.h would
    fail the whole firmware build over something that should only ever
    degrade the *IDN? reply, not block compiling."""
    try:
        result = subprocess.run(
            ["git", "-C", PROJECT_DIR] + args,
            capture_output=True, text=True, timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def main():
    commit = run_git(["rev-parse", f"--short={HASH_LEN}", "HEAD"])
    if commit is None:
        # Not a git repo, git not installed, or no commits yet -- still
        # write a valid header (a real firmware build must not be
        # blocked by this), just an honest "we don't actually know".
        commit = "unknown"
        dirty = 0
        print("[warn] couldn't determine git commit (not a git repo, no git on "
              "PATH, or no commits yet) -- writing FW_GIT_COMMIT \"unknown\"",
              file=sys.stderr)
    else:
        # Non-empty `git status --porcelain` output means the working
        # tree has uncommitted changes relative to `commit` above --
        # flagged explicitly rather than silently reporting a commit
        # hash that doesn't actually match what's running (see
        # commands.c's cmd_idn() for how this renders in *IDN?).
        status = run_git(["status", "--porcelain"])
        dirty = 1 if status else 0

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write(
            "/* AUTO-GENERATED by python/gen_git_version.py -- DO NOT EDIT BY\n"
            " * HAND, DO NOT COMMIT (gitignored, see .gitignore's own comment\n"
            " * on why). Regenerated before every build by python/wham_build.py.\n"
            " * Included by commands.c's cmd_idn() so *IDN? reports exactly\n"
            " * which commit this firmware was built from. */\n"
            "#ifndef GIT_VERSION_H\n"
            "#define GIT_VERSION_H\n"
            "\n"
            f'#define FW_GIT_COMMIT "{commit}"\n'
            f"#define FW_GIT_DIRTY   {dirty}U   /* 1 if the working tree had "
            "uncommitted changes at build time */\n"
            "\n"
            "#endif /* GIT_VERSION_H */\n"
        )

    tag = f"{commit}{'-dirty' if dirty else ''}"
    print(f"[git-version] wrote {OUT_PATH} -- FW_GIT_COMMIT={tag}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
